// This file is auto-generated by @hey-api/openapi-ts

/**
 * Agent
 */
export type Agent = {
    /**
     * Agent Id
     * Unique identifier of the model.
     */
    agent_id: string;
    /**
     * Agent Version
     * Version of the agent.
     */
    agent_version: number;
    /**
     * Name
     * Username of the user.
     */
    name: string;
    /**
     * Tags
     * List of tags associated with the agent.
     */
    tags?: Array<string>;
    /**
     * Icon Link
     * Link to the user's icon or avatar, if available.
     */
    icon_link?: string | null;
};

/**
 * AgentDetail
 */
export type AgentDetail = {
    /**
     * Agent Id
     * Unique identifier of the agent.
     */
    agent_id: string;
    /**
     * Agent Version
     * Version of the agent.
     */
    agent_version: number;
    /**
     * Author Name
     * Name of the author of the agent.
     */
    author_name: string | null;
    /**
     * Name
     * Name of the agent.
     */
    name: string;
    /**
     * Description
     * Description of the agent, if available.
     */
    description: string;
    /**
     * Icon Link
     * Link to the agent's icon or avatar, if available.
     */
    icon_link?: string | null;
    /**
     * Tags
     * List of tags associated with the agent.
     */
    tags?: Array<string>;
    /**
     * Prompt
     * Prompt or instructions for the agent, if available.
     */
    prompt?: string | null;
    /**
     * Created At
     * Timestamp when the agent was created.
     */
    created_at: string;
    /**
     * Updated At
     * Timestamp when the agent was last updated.
     */
    updated_at: string;
};

/**
 * AgentMarketPlace
 */
export type AgentMarketPlace = {
    /**
     * Agent Id
     * Unique identifier of the model.
     */
    agent_id: string;
    /**
     * Agent Version
     * Version of the agent.
     */
    agent_version: number;
    /**
     * Name
     * Username of the user.
     */
    name: string;
    /**
     * Tags
     * List of tags associated with the agent.
     */
    tags?: Array<string>;
    /**
     * Icon Link
     * Link to the user's icon or avatar, if available.
     */
    icon_link?: string | null;
    /**
     * Subscribed
     * Indicates whether the user is subscribed to this agent.
     */
    subscribed?: boolean;
};

/**
 * AgentPublish
 */
export type AgentPublish = {
    /**
     * Agent Id
     * Unique identifier of the agent. If not provided, a new ID will be generated.
     */
    agent_id?: string | null;
    /**
     * Name
     * Name of the agent.
     */
    name: string;
    /**
     * Icon Link
     * Link to the agent's icon or avatar, if available.
     */
    icon_link?: string | null;
    /**
     * Tags
     * List of tags associated with the agent.
     */
    tags?: Array<string>;
    /**
     * Description
     * Description of the agent, if available.
     */
    description: string;
    /**
     * Prompt
     * Prompt or instructions for the agent.
     */
    prompt: string;
    /**
     * Output Schema
     * Output schema for the agent's responses. if not provided, it will be raw string
     */
    output_schema?: Array<Attribute> | null;
};

/**
 * Attribute
 * Represents an attribute for the output schema of an agent's response.
 */
export type Attribute = {
    /**
     * Attribute
     * attribute for the output schema
     */
    attribute: string;
    /**
     * Type
     * type of the output schema, e.g., 'str', 'int', 'float', 'bool'.
     */
    type: string;
};

/**
 * BaseResponse
 * Base response model for API responses.
 */
export type BaseResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
};

/**
 * Content
 * Content model for messages
 */
export type Content = {
    /**
     * Type
     * Type of the message content, e.g., 'text'.
     */
    type?: 'text' | 'image' | 'file';
    /**
     * Parts
     * List of parts that make up the message content.
     */
    parts?: Array<string>;
};

/**
 * ConversationMaster
 */
export type ConversationMaster = {
    /**
     * Conversation Id
     * Unique identifier of the model.
     */
    conversation_id: string;
    /**
     * Title
     * Username of the user.
     */
    title: string;
    /**
     * Icon
     * Link to the user's icon or avatar, if available.
     */
    icon?: string | null;
    /**
     * Created At
     * Creation timestamp of the conversation.
     */
    created_at: string;
    /**
     * Updated At
     * Last updated timestamp of the conversation.
     */
    updated_at: string;
};

/**
 * GetAgentResponse
 * GET /api/v1/agents/{agent_id} Response model
 */
export type GetAgentResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
    /**
     * Details of the requested agent.
     */
    agent: AgentDetail;
};

/**
 * GetAvailableAgentsResponse
 * GET /api/v1/agents Response model
 */
export type GetAvailableAgentsResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
    /**
     * Agents
     * List of available agents.
     */
    agents?: Array<AgentMarketPlace>;
    /**
     * Total
     * Total number of agents matching the query.
     */
    total: number;
    /**
     * Page
     * Current page number.
     */
    page: number;
    /**
     * Size
     * Number of items per page.
     */
    size: number;
    /**
     * Has Next
     * Whether there is a next page.
     */
    has_next: boolean;
};

/**
 * GetConversationResponse
 * GET /api/v1/conversation Response model
 */
export type GetConversationResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
    /**
     * List of conversations associated with the user.
     */
    conversation: ConversationMaster;
    /**
     * Messages
     * List of messages in the conversation.
     */
    messages?: Array<MessageResponse>;
};

/**
 * GetConversationsResponse
 * GET /api/v1/conversations Response model
 */
export type GetConversationsResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
    /**
     * Conversations
     * List of conversations associated with the user.
     */
    conversations?: Array<ConversationMaster>;
};

/**
 * GetMeResponse
 * GET /api/v1/user Response model
 */
export type GetMeResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
    /**
     * User information model containing details about the current user.
     */
    user: User;
    /**
     * Agents
     * List of agent IDs that the user is subscribed to.
     */
    agents?: Array<Agent>;
    /**
     * Llms
     * List of model IDs that the user has access to.
     */
    llms?: Array<LlmModel>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LLMModel
 */
export type LlmModel = {
    /**
     * Issuer
     * The issuer of the LLM model, e.g., 'openai', 'anthropic'.
     */
    issuer: string;
    /**
     * Deployment Id
     * Deployment identifier for the model.
     */
    deployment_id: string;
    /**
     * Name
     * Username of the user.
     */
    name: string;
    /**
     * Description
     * Description of the model, if available.
     */
    description: string;
    /**
     * Icon Link
     * Link to the user's icon or avatar, if available.
     */
    icon_link?: string | null;
};

/**
 * LLMModelRequest
 * Request model for LLM model operations.
 */
export type LlmModelRequest = {
    /**
     * Issuer
     * The issuer of the LLM model, e.g., 'openai', 'anthropic'.
     */
    issuer: string;
    /**
     * Deployment Id
     * Deployment identifier for the model.
     */
    deployment_id: string;
};

/**
 * MessageRequest
 */
export type MessageRequest = {
    content: Content;
};

/**
 * MessageResponse
 * Message model representing a single message in a conversation.
 */
export type MessageResponse = {
    /**
     * Message Id
     * Unique identifier of the message.
     */
    message_id: string;
    /**
     * Parent Message Id
     * ID of the parent message, if this message is a reply.
     */
    parent_message_id?: string | null;
    /**
     * Agent Id
     * ID of the agent that sent the message, if applicable.
     */
    agent_id?: string | null;
    /**
     * Role
     * Role of the message sender, e.g., 'user' or 'assistant'.
     */
    role: 'user' | 'assistant';
    /**
     * Content of the message.
     */
    content: Content;
    /**
     * The deployment id of model used to generate the message.
     */
    llm: LlmModel | null;
    /**
     * Created At
     * Creation timestamp of the message.
     */
    created_at: string;
    /**
     * Updated At
     * Last updated timestamp of the message.
     */
    updated_at: string;
};

/**
 * PostGenerateCompletionRequest
 * POST /api/v1/completion Request model
 */
export type PostGenerateCompletionRequest = {
    /**
     * Action
     * Action to be performed for the completion request, e.g., 'next', 'retry', or 'variant'.
     */
    action: 'next' | 'retry' | 'variant';
    /**
     * Conversation Id
     * ID of the conversation for which the completion is requested.
     */
    conversation_id: string;
    /**
     * Parent Message Id
     * ID of the parent message for the completion request.
     */
    parent_message_id: string | null;
    /**
     * Agent Id
     * ID of the agent to use for generating the completion.
     */
    agent_id: string;
    /**
     * Agent Version
     * Version of the agent to use for generating the completion.
     */
    agent_version?: number;
    /**
     * Model Deployment ID to be used for generating the completion.
     */
    llm: LlmModelRequest;
    /**
     * Messages
     * List of messages in the conversation for which the completion is requested.
     */
    messages: Array<MessageRequest>;
};

/**
 * PostPublishAgentRequest
 * POST /api/v1/agent/publish Request model
 */
export type PostPublishAgentRequest = {
    /**
     * Details of the agent to be published.
     */
    agent: AgentPublish;
};

/**
 * PostPublishAgentResponse
 * POST /api/v1/agent/publish Response model
 */
export type PostPublishAgentResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
};

/**
 * PostSubscribeAgentResponse
 * POST /api/v1/agent/agent_id/subscribe Response model
 */
export type PostSubscribeAgentResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
};

/**
 * PutModifyAgentRequest
 * POST /api/v1/agent/publish Request model
 */
export type PutModifyAgentRequest = {
    /**
     * Details of the agent to be published.
     */
    agent: AgentPublish;
};

/**
 * PutModifyAgentResponse
 * PUT /api/v1/agent/agent_id Response model
 */
export type PutModifyAgentResponse = {
    /**
     * Status
     * Status of the response, e.g., 'success' or 'error'.
     */
    status?: 'success' | 'error';
    /**
     * Message
     * Message providing additional information about the response.
     */
    message?: string;
    /**
     * Request Id
     * Unique identifier for the request, used for tracking and debugging.
     */
    request_id: string;
};

/**
 * User
 */
export type User = {
    /**
     * User Id
     * Unique identifier of the user.
     */
    user_id: string;
    /**
     * Username
     * Username of the user.
     */
    username: string;
    /**
     * Email
     * Email address of the user, if available.
     */
    email?: string | null;
    /**
     * Icon Link
     * Link to the user's icon or avatar, if available.
     */
    icon_link?: string | null;
    /**
     * Is Superuser
     * Flag indicating whether the user has superuser privileges.
     */
    is_superuser?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: BaseResponse;
};

export type ReadRootGetResponse = ReadRootGetResponses[keyof ReadRootGetResponses];

export type GetMeApiV1UserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type GetMeApiV1UserGetResponses = {
    /**
     * Successful Response
     */
    200: GetMeResponse;
};

export type GetMeApiV1UserGetResponse = GetMeApiV1UserGetResponses[keyof GetMeApiV1UserGetResponses];

export type GetConversationsApiV1ConversationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/conversations';
};

export type GetConversationsApiV1ConversationsGetResponses = {
    /**
     * Successful Response
     */
    200: GetConversationsResponse;
};

export type GetConversationsApiV1ConversationsGetResponse = GetConversationsApiV1ConversationsGetResponses[keyof GetConversationsApiV1ConversationsGetResponses];

export type GetConversationApiV1ConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}';
};

export type GetConversationApiV1ConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiV1ConversationsConversationIdGetError = GetConversationApiV1ConversationsConversationIdGetErrors[keyof GetConversationApiV1ConversationsConversationIdGetErrors];

export type GetConversationApiV1ConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetConversationResponse;
};

export type GetConversationApiV1ConversationsConversationIdGetResponse = GetConversationApiV1ConversationsConversationIdGetResponses[keyof GetConversationApiV1ConversationsConversationIdGetResponses];

export type GetAvailableAgentsApiV1AgentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
    };
    url: '/api/v1/agents';
};

export type GetAvailableAgentsApiV1AgentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAvailableAgentsApiV1AgentsGetError = GetAvailableAgentsApiV1AgentsGetErrors[keyof GetAvailableAgentsApiV1AgentsGetErrors];

export type GetAvailableAgentsApiV1AgentsGetResponses = {
    /**
     * Successful Response
     */
    200: GetAvailableAgentsResponse;
};

export type GetAvailableAgentsApiV1AgentsGetResponse = GetAvailableAgentsApiV1AgentsGetResponses[keyof GetAvailableAgentsApiV1AgentsGetResponses];

export type GetAgentApiV1AgentsAgentIdVersionAgentVersionGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Agent Version
         */
        agent_version: number;
    };
    query?: never;
    url: '/api/v1/agents/{agent_id}/version/{agent_version}';
};

export type GetAgentApiV1AgentsAgentIdVersionAgentVersionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentApiV1AgentsAgentIdVersionAgentVersionGetError = GetAgentApiV1AgentsAgentIdVersionAgentVersionGetErrors[keyof GetAgentApiV1AgentsAgentIdVersionAgentVersionGetErrors];

export type GetAgentApiV1AgentsAgentIdVersionAgentVersionGetResponses = {
    /**
     * Successful Response
     */
    200: GetAgentResponse;
};

export type GetAgentApiV1AgentsAgentIdVersionAgentVersionGetResponse = GetAgentApiV1AgentsAgentIdVersionAgentVersionGetResponses[keyof GetAgentApiV1AgentsAgentIdVersionAgentVersionGetResponses];

export type SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
        /**
         * Agent Version
         */
        agent_version: number;
    };
    query?: never;
    url: '/api/v1/agents/{agent_id}/version/{agent_version}/subscribe';
};

export type SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostError = SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostErrors[keyof SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostErrors];

export type SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostResponses = {
    /**
     * Successful Response
     */
    200: PostSubscribeAgentResponse;
};

export type SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostResponse = SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostResponses[keyof SubscribeAgentApiV1AgentsAgentIdVersionAgentVersionSubscribePostResponses];

export type PublishAgentApiV1AgentsPublishPostData = {
    body: PostPublishAgentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agents/publish';
};

export type PublishAgentApiV1AgentsPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishAgentApiV1AgentsPublishPostError = PublishAgentApiV1AgentsPublishPostErrors[keyof PublishAgentApiV1AgentsPublishPostErrors];

export type PublishAgentApiV1AgentsPublishPostResponses = {
    /**
     * Successful Response
     */
    200: PostPublishAgentResponse;
};

export type PublishAgentApiV1AgentsPublishPostResponse = PublishAgentApiV1AgentsPublishPostResponses[keyof PublishAgentApiV1AgentsPublishPostResponses];

export type ModifyAgentApiV1AgentsAgentIdPutData = {
    body: PutModifyAgentRequest;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/agents/{agent_id}';
};

export type ModifyAgentApiV1AgentsAgentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModifyAgentApiV1AgentsAgentIdPutError = ModifyAgentApiV1AgentsAgentIdPutErrors[keyof ModifyAgentApiV1AgentsAgentIdPutErrors];

export type ModifyAgentApiV1AgentsAgentIdPutResponses = {
    /**
     * Successful Response
     */
    200: PutModifyAgentResponse;
};

export type ModifyAgentApiV1AgentsAgentIdPutResponse = ModifyAgentApiV1AgentsAgentIdPutResponses[keyof ModifyAgentApiV1AgentsAgentIdPutResponses];

export type GenerateCompletionApiV1CompletionPostData = {
    body: PostGenerateCompletionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/completion';
};

export type GenerateCompletionApiV1CompletionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateCompletionApiV1CompletionPostError = GenerateCompletionApiV1CompletionPostErrors[keyof GenerateCompletionApiV1CompletionPostErrors];

export type GenerateCompletionApiV1CompletionPostResponses = {
    /**
     * Streaming response containing the generated completion.
     */
    200: string;
};

export type GenerateCompletionApiV1CompletionPostResponse = GenerateCompletionApiV1CompletionPostResponses[keyof GenerateCompletionApiV1CompletionPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};